[package]

name = "node_rs"
version = "0.0.0"
authors = [ "Caleb James DeLisle" ]
description = "NodeJS-like event loop environment for Rust"
license = "MIT"

[dependencies]
mio = "0.6.15"
mio-extras = "2.0.5"
